# Generated by Django 5.0.6 on 2025-02-08 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_user_manager"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Manager",
        ),
    ]
