# Generated by Django 5.0.6 on 2025-02-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="email",
            field=models.EmailField(default=0, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="manager",
            name="name",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
