# Generated by Django 5.0.6 on 2025-02-21 12:29

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_userprofile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="image",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(
                upload_to='default/path/',
                blank=True,
                null=True
            ),
        ),
    ]
