# Generated by Django 5.0.6 on 2025-02-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="ticket_name",
            field=models.CharField(default="none", max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="ticket_type",
            field=models.CharField(default="none", max_length=100),
        ),
    ]
